/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_FTM1CH0SRC_FTM 0x00u     /*!<@brief FTM1 channel 0 input capture source select: FTM1_CH0 signal */
#define SOPT4_FTM1CLKSEL_CLK0 0x00u    /*!<@brief FTM1 External Clock Pin Select: FTM_CLK0 pin */
#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART 1 transmit data source select: UART1_TX pin */

/*! @name PORTC4 (number 49), ES_RST
  @{ */
#define BOARD_ES_RST_PERIPHERAL GPIOC                   /*!<@brief Device name: GPIOC */
#define BOARD_ES_RST_SIGNAL GPIO                        /*!<@brief GPIOC signal: GPIO */
#define BOARD_ES_RST_GPIO GPIOC                         /*!<@brief GPIO device name: GPIOC */
#define BOARD_ES_RST_GPIO_PIN 4U                        /*!<@brief PORTC pin index: 4 */
#define BOARD_ES_RST_PORT PORTC                         /*!<@brief PORT device name: PORTC */
#define BOARD_ES_RST_PIN 4U                             /*!<@brief PORTC pin index: 4 */
#define BOARD_ES_RST_CHANNEL 4                          /*!<@brief GPIOC GPIO channel: 4 */
#define BOARD_ES_RST_PIN_NAME PTC4                      /*!<@brief Pin name */
#define BOARD_ES_RST_LABEL "ES_RST"                     /*!<@brief Label */
#define BOARD_ES_RST_NAME "ES_RST"                      /*!<@brief Identifier name */
#define BOARD_ES_RST_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                        /* @} */

/*! @name PORTC8 (number 53), ES_SCK_EN
  @{ */
#define BOARD_ES_SCK_EN_PERIPHERAL GPIOC                   /*!<@brief Device name: GPIOC */
#define BOARD_ES_SCK_EN_SIGNAL GPIO                        /*!<@brief GPIOC signal: GPIO */
#define BOARD_ES_SCK_EN_GPIO GPIOC                         /*!<@brief GPIO device name: GPIOC */
#define BOARD_ES_SCK_EN_GPIO_PIN 8U                        /*!<@brief PORTC pin index: 8 */
#define BOARD_ES_SCK_EN_PORT PORTC                         /*!<@brief PORT device name: PORTC */
#define BOARD_ES_SCK_EN_PIN 8U                             /*!<@brief PORTC pin index: 8 */
#define BOARD_ES_SCK_EN_CHANNEL 8                          /*!<@brief GPIOC GPIO channel: 8 */
#define BOARD_ES_SCK_EN_PIN_NAME PTC8                      /*!<@brief Pin name */
#define BOARD_ES_SCK_EN_LABEL "ES_SCK_EN"                  /*!<@brief Label */
#define BOARD_ES_SCK_EN_NAME "ES_SCK_EN"                   /*!<@brief Identifier name */
#define BOARD_ES_SCK_EN_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                           /* @} */

/*! @name PORTC9 (number 54), ES_DO_EN
  @{ */
#define BOARD_ES_DO_EN_PERIPHERAL GPIOC                   /*!<@brief Device name: GPIOC */
#define BOARD_ES_DO_EN_SIGNAL GPIO                        /*!<@brief GPIOC signal: GPIO */
#define BOARD_ES_DO_EN_GPIO GPIOC                         /*!<@brief GPIO device name: GPIOC */
#define BOARD_ES_DO_EN_GPIO_PIN 9U                        /*!<@brief PORTC pin index: 9 */
#define BOARD_ES_DO_EN_PORT PORTC                         /*!<@brief PORT device name: PORTC */
#define BOARD_ES_DO_EN_PIN 9U                             /*!<@brief PORTC pin index: 9 */
#define BOARD_ES_DO_EN_CHANNEL 9                          /*!<@brief GPIOC GPIO channel: 9 */
#define BOARD_ES_DO_EN_PIN_NAME PTC9                      /*!<@brief Pin name */
#define BOARD_ES_DO_EN_LABEL "ES_DO_EN"                   /*!<@brief Label */
#define BOARD_ES_DO_EN_NAME "ES_DO_EN"                    /*!<@brief Identifier name */
#define BOARD_ES_DO_EN_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                          /* @} */

/*! @name PORTC10 (number 55), ES_CTL_IO
  @{ */
#define BOARD_ES_CTL_IO_PERIPHERAL GPIOC                   /*!<@brief Device name: GPIOC */
#define BOARD_ES_CTL_IO_SIGNAL GPIO                        /*!<@brief GPIOC signal: GPIO */
#define BOARD_ES_CTL_IO_GPIO GPIOC                         /*!<@brief GPIO device name: GPIOC */
#define BOARD_ES_CTL_IO_GPIO_PIN 10U                       /*!<@brief PORTC pin index: 10 */
#define BOARD_ES_CTL_IO_PORT PORTC                         /*!<@brief PORT device name: PORTC */
#define BOARD_ES_CTL_IO_PIN 10U                            /*!<@brief PORTC pin index: 10 */
#define BOARD_ES_CTL_IO_CHANNEL 10                         /*!<@brief GPIOC GPIO channel: 10 */
#define BOARD_ES_CTL_IO_PIN_NAME PTC10                     /*!<@brief Pin name */
#define BOARD_ES_CTL_IO_LABEL "ES_CTL_IO"                  /*!<@brief Label */
#define BOARD_ES_CTL_IO_NAME "ES_CTL_IO"                   /*!<@brief Identifier name */
#define BOARD_ES_CTL_IO_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                           /* @} */

/*! @name PORTA1 (number 23), KEY0
  @{ */
#define BOARD_KEY0_PERIPHERAL GPIOA                  /*!<@brief Device name: GPIOA */
#define BOARD_KEY0_SIGNAL GPIO                       /*!<@brief GPIOA signal: GPIO */
#define BOARD_KEY0_GPIO GPIOA                        /*!<@brief GPIO device name: GPIOA */
#define BOARD_KEY0_GPIO_PIN 1U                       /*!<@brief PORTA pin index: 1 */
#define BOARD_KEY0_PORT PORTA                        /*!<@brief PORT device name: PORTA */
#define BOARD_KEY0_PIN 1U                            /*!<@brief PORTA pin index: 1 */
#define BOARD_KEY0_CHANNEL 1                         /*!<@brief GPIOA GPIO channel: 1 */
#define BOARD_KEY0_PIN_NAME PTA1                     /*!<@brief Pin name */
#define BOARD_KEY0_LABEL "KEY0"                      /*!<@brief Label */
#define BOARD_KEY0_NAME "KEY0"                       /*!<@brief Identifier name */
#define BOARD_KEY0_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                     /* @} */

/*! @name PORTA2 (number 24), KEY2
  @{ */
#define BOARD_KEY2_PERIPHERAL GPIOA                  /*!<@brief Device name: GPIOA */
#define BOARD_KEY2_SIGNAL GPIO                       /*!<@brief GPIOA signal: GPIO */
#define BOARD_KEY2_GPIO GPIOA                        /*!<@brief GPIO device name: GPIOA */
#define BOARD_KEY2_GPIO_PIN 2U                       /*!<@brief PORTA pin index: 2 */
#define BOARD_KEY2_PORT PORTA                        /*!<@brief PORT device name: PORTA */
#define BOARD_KEY2_PIN 2U                            /*!<@brief PORTA pin index: 2 */
#define BOARD_KEY2_CHANNEL 2                         /*!<@brief GPIOA GPIO channel: 2 */
#define BOARD_KEY2_PIN_NAME PTA2                     /*!<@brief Pin name */
#define BOARD_KEY2_LABEL "KEY2"                      /*!<@brief Label */
#define BOARD_KEY2_NAME "KEY2"                       /*!<@brief Identifier name */
#define BOARD_KEY2_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                     /* @} */

/*! @name PORTA4 (number 26), KEY1
  @{ */
#define BOARD_KEY1_PERIPHERAL GPIOA                  /*!<@brief Device name: GPIOA */
#define BOARD_KEY1_SIGNAL GPIO                       /*!<@brief GPIOA signal: GPIO */
#define BOARD_KEY1_GPIO GPIOA                        /*!<@brief GPIO device name: GPIOA */
#define BOARD_KEY1_GPIO_PIN 4U                       /*!<@brief PORTA pin index: 4 */
#define BOARD_KEY1_PORT PORTA                        /*!<@brief PORT device name: PORTA */
#define BOARD_KEY1_PIN 4U                            /*!<@brief PORTA pin index: 4 */
#define BOARD_KEY1_CHANNEL 4                         /*!<@brief GPIOA GPIO channel: 4 */
#define BOARD_KEY1_PIN_NAME PTA4                     /*!<@brief Pin name */
#define BOARD_KEY1_LABEL "KEY1"                      /*!<@brief Label */
#define BOARD_KEY1_NAME "KEY1"                       /*!<@brief Identifier name */
#define BOARD_KEY1_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                     /* @} */

/*! @name PORTA5 (number 27), LED_G/PASS_OUT
  @{ */
#define BOARD_LED_G_PASS_PERIPHERAL GPIOA                   /*!<@brief Device name: GPIOA */
#define BOARD_LED_G_PASS_SIGNAL GPIO                        /*!<@brief GPIOA signal: GPIO */
#define BOARD_LED_G_PASS_GPIO GPIOA                         /*!<@brief GPIO device name: GPIOA */
#define BOARD_LED_G_PASS_GPIO_PIN 5U                        /*!<@brief PORTA pin index: 5 */
#define BOARD_LED_G_PASS_PORT PORTA                         /*!<@brief PORT device name: PORTA */
#define BOARD_LED_G_PASS_PIN 5U                             /*!<@brief PORTA pin index: 5 */
#define BOARD_LED_G_PASS_CHANNEL 5                          /*!<@brief GPIOA GPIO channel: 5 */
#define BOARD_LED_G_PASS_PIN_NAME PTA5                      /*!<@brief Pin name */
#define BOARD_LED_G_PASS_LABEL "LED_G/PASS_OUT"             /*!<@brief Label */
#define BOARD_LED_G_PASS_NAME "LED_G_PASS"                  /*!<@brief Identifier name */
#define BOARD_LED_G_PASS_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                            /* @} */

/*! @name PORTB2 (number 37), LED_R/ERROR_OUT
  @{ */
#define BOARD_LED_R_ERROR_PERIPHERAL GPIOB                   /*!<@brief Device name: GPIOB */
#define BOARD_LED_R_ERROR_SIGNAL GPIO                        /*!<@brief GPIOB signal: GPIO */
#define BOARD_LED_R_ERROR_GPIO GPIOB                         /*!<@brief GPIO device name: GPIOB */
#define BOARD_LED_R_ERROR_GPIO_PIN 2U                        /*!<@brief PORTB pin index: 2 */
#define BOARD_LED_R_ERROR_PORT PORTB                         /*!<@brief PORT device name: PORTB */
#define BOARD_LED_R_ERROR_PIN 2U                             /*!<@brief PORTB pin index: 2 */
#define BOARD_LED_R_ERROR_CHANNEL 2                          /*!<@brief GPIOB GPIO channel: 2 */
#define BOARD_LED_R_ERROR_PIN_NAME PTB2                      /*!<@brief Pin name */
#define BOARD_LED_R_ERROR_LABEL "LED_R/ERROR_OUT"            /*!<@brief Label */
#define BOARD_LED_R_ERROR_NAME "LED_R_ERROR"                 /*!<@brief Identifier name */
#define BOARD_LED_R_ERROR_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                             /* @} */

/*! @name PORTB3 (number 38), LED_Y/BUSY_OUT
  @{ */
#define BOARD_LED_Y_BUSY_PERIPHERAL GPIOB                   /*!<@brief Device name: GPIOB */
#define BOARD_LED_Y_BUSY_SIGNAL GPIO                        /*!<@brief GPIOB signal: GPIO */
#define BOARD_LED_Y_BUSY_GPIO GPIOB                         /*!<@brief GPIO device name: GPIOB */
#define BOARD_LED_Y_BUSY_GPIO_PIN 3U                        /*!<@brief PORTB pin index: 3 */
#define BOARD_LED_Y_BUSY_PORT PORTB                         /*!<@brief PORT device name: PORTB */
#define BOARD_LED_Y_BUSY_PIN 3U                             /*!<@brief PORTB pin index: 3 */
#define BOARD_LED_Y_BUSY_CHANNEL 3                          /*!<@brief GPIOB GPIO channel: 3 */
#define BOARD_LED_Y_BUSY_PIN_NAME PTB3                      /*!<@brief Pin name */
#define BOARD_LED_Y_BUSY_LABEL "LED_Y/BUSY_OUT"             /*!<@brief Label */
#define BOARD_LED_Y_BUSY_NAME "LED_Y_BUSY"                  /*!<@brief Identifier name */
#define BOARD_LED_Y_BUSY_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                            /* @} */

/*! @name PORTB18 (number 41), OLED_CS
  @{ */
#define BOARD_OLED_CS_PERIPHERAL GPIOB                   /*!<@brief Device name: GPIOB */
#define BOARD_OLED_CS_SIGNAL GPIO                        /*!<@brief GPIOB signal: GPIO */
#define BOARD_OLED_CS_GPIO GPIOB                         /*!<@brief GPIO device name: GPIOB */
#define BOARD_OLED_CS_GPIO_PIN 18U                       /*!<@brief PORTB pin index: 18 */
#define BOARD_OLED_CS_PORT PORTB                         /*!<@brief PORT device name: PORTB */
#define BOARD_OLED_CS_PIN 18U                            /*!<@brief PORTB pin index: 18 */
#define BOARD_OLED_CS_CHANNEL 18                         /*!<@brief GPIOB GPIO channel: 18 */
#define BOARD_OLED_CS_PIN_NAME PTB18                     /*!<@brief Pin name */
#define BOARD_OLED_CS_LABEL "OLED_CS"                    /*!<@brief Label */
#define BOARD_OLED_CS_NAME "OLED_CS"                     /*!<@brief Identifier name */
#define BOARD_OLED_CS_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                         /* @} */

/*! @name PORTB19 (number 42), OLED_RST
  @{ */
#define BOARD_OLED_RST_PERIPHERAL GPIOB                   /*!<@brief Device name: GPIOB */
#define BOARD_OLED_RST_SIGNAL GPIO                        /*!<@brief GPIOB signal: GPIO */
#define BOARD_OLED_RST_GPIO GPIOB                         /*!<@brief GPIO device name: GPIOB */
#define BOARD_OLED_RST_GPIO_PIN 19U                       /*!<@brief PORTB pin index: 19 */
#define BOARD_OLED_RST_PORT PORTB                         /*!<@brief PORT device name: PORTB */
#define BOARD_OLED_RST_PIN 19U                            /*!<@brief PORTB pin index: 19 */
#define BOARD_OLED_RST_CHANNEL 19                         /*!<@brief GPIOB GPIO channel: 19 */
#define BOARD_OLED_RST_PIN_NAME PTB19                     /*!<@brief Pin name */
#define BOARD_OLED_RST_LABEL "OLED_RST"                   /*!<@brief Label */
#define BOARD_OLED_RST_NAME "OLED_RST"                    /*!<@brief Identifier name */
#define BOARD_OLED_RST_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                          /* @} */

/*! @name PORTC2 (number 45), OLED_SCK
  @{ */
#define BOARD_OLED_SCK_PERIPHERAL GPIOC                   /*!<@brief Device name: GPIOC */
#define BOARD_OLED_SCK_SIGNAL GPIO                        /*!<@brief GPIOC signal: GPIO */
#define BOARD_OLED_SCK_GPIO GPIOC                         /*!<@brief GPIO device name: GPIOC */
#define BOARD_OLED_SCK_GPIO_PIN 2U                        /*!<@brief PORTC pin index: 2 */
#define BOARD_OLED_SCK_PORT PORTC                         /*!<@brief PORT device name: PORTC */
#define BOARD_OLED_SCK_PIN 2U                             /*!<@brief PORTC pin index: 2 */
#define BOARD_OLED_SCK_CHANNEL 2                          /*!<@brief GPIOC GPIO channel: 2 */
#define BOARD_OLED_SCK_PIN_NAME PTC2                      /*!<@brief Pin name */
#define BOARD_OLED_SCK_LABEL "OLED_SCK"                   /*!<@brief Label */
#define BOARD_OLED_SCK_NAME "OLED_SCK"                    /*!<@brief Identifier name */
#define BOARD_OLED_SCK_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                          /* @} */

/*! @name PORTC3 (number 46), OLED_SDA
  @{ */
#define BOARD_OLED_SDA_PERIPHERAL GPIOC                   /*!<@brief Device name: GPIOC */
#define BOARD_OLED_SDA_SIGNAL GPIO                        /*!<@brief GPIOC signal: GPIO */
#define BOARD_OLED_SDA_GPIO GPIOC                         /*!<@brief GPIO device name: GPIOC */
#define BOARD_OLED_SDA_GPIO_PIN 3U                        /*!<@brief PORTC pin index: 3 */
#define BOARD_OLED_SDA_PORT PORTC                         /*!<@brief PORT device name: PORTC */
#define BOARD_OLED_SDA_PIN 3U                             /*!<@brief PORTC pin index: 3 */
#define BOARD_OLED_SDA_CHANNEL 3                          /*!<@brief GPIOC GPIO channel: 3 */
#define BOARD_OLED_SDA_PIN_NAME PTC3                      /*!<@brief Pin name */
#define BOARD_OLED_SDA_LABEL "OLED_SDA"                   /*!<@brief Label */
#define BOARD_OLED_SDA_NAME "OLED_SDA"                    /*!<@brief Identifier name */
#define BOARD_OLED_SDA_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                          /* @} */

/*! @name PORTD3 (number 60), BEEP
  @{ */
#define BOARD_BEEP_PERIPHERAL GPIOD                   /*!<@brief Device name: GPIOD */
#define BOARD_BEEP_SIGNAL GPIO                        /*!<@brief GPIOD signal: GPIO */
#define BOARD_BEEP_GPIO GPIOD                         /*!<@brief GPIO device name: GPIOD */
#define BOARD_BEEP_GPIO_PIN 3U                        /*!<@brief PORTD pin index: 3 */
#define BOARD_BEEP_PORT PORTD                         /*!<@brief PORT device name: PORTD */
#define BOARD_BEEP_PIN 3U                             /*!<@brief PORTD pin index: 3 */
#define BOARD_BEEP_CHANNEL 3                          /*!<@brief GPIOD GPIO channel: 3 */
#define BOARD_BEEP_PIN_NAME PTD3                      /*!<@brief Pin name */
#define BOARD_BEEP_LABEL "BEEP"                       /*!<@brief Label */
#define BOARD_BEEP_NAME "BEEP"                        /*!<@brief Identifier name */
#define BOARD_BEEP_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                      /* @} */

/*! @name PORTD0 (number 57), SELECT_5V
  @{ */
#define BOARD_SELECT_5V_PERIPHERAL GPIOD                   /*!<@brief Device name: GPIOD */
#define BOARD_SELECT_5V_SIGNAL GPIO                        /*!<@brief GPIOD signal: GPIO */
#define BOARD_SELECT_5V_GPIO GPIOD                         /*!<@brief GPIO device name: GPIOD */
#define BOARD_SELECT_5V_GPIO_PIN 0U                        /*!<@brief PORTD pin index: 0 */
#define BOARD_SELECT_5V_PORT PORTD                         /*!<@brief PORT device name: PORTD */
#define BOARD_SELECT_5V_PIN 0U                             /*!<@brief PORTD pin index: 0 */
#define BOARD_SELECT_5V_CHANNEL 0                          /*!<@brief GPIOD GPIO channel: 0 */
#define BOARD_SELECT_5V_PIN_NAME PTD0                      /*!<@brief Pin name */
#define BOARD_SELECT_5V_LABEL "SELECT_5V"                  /*!<@brief Label */
#define BOARD_SELECT_5V_NAME "SELECT_5V"                   /*!<@brief Identifier name */
#define BOARD_SELECT_5V_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                           /* @} */

/*! @name PORTD1 (number 58), SELECT_3V3
  @{ */
#define BOARD_SELECT_3V3_PERIPHERAL GPIOD                   /*!<@brief Device name: GPIOD */
#define BOARD_SELECT_3V3_SIGNAL GPIO                        /*!<@brief GPIOD signal: GPIO */
#define BOARD_SELECT_3V3_GPIO GPIOD                         /*!<@brief GPIO device name: GPIOD */
#define BOARD_SELECT_3V3_GPIO_PIN 1U                        /*!<@brief PORTD pin index: 1 */
#define BOARD_SELECT_3V3_PORT PORTD                         /*!<@brief PORT device name: PORTD */
#define BOARD_SELECT_3V3_PIN 1U                             /*!<@brief PORTD pin index: 1 */
#define BOARD_SELECT_3V3_CHANNEL 1                          /*!<@brief GPIOD GPIO channel: 1 */
#define BOARD_SELECT_3V3_PIN_NAME PTD1                      /*!<@brief Pin name */
#define BOARD_SELECT_3V3_LABEL "SELECT_3V3"                 /*!<@brief Label */
#define BOARD_SELECT_3V3_NAME "SELECT_3V3"                  /*!<@brief Identifier name */
#define BOARD_SELECT_3V3_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
